name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bingtsingw/composite-actions/pnpm-install@v1
      - run: |
          pnpm run check-mono
          pnpm run build
          pnpm run format
          pnpm run lint:js
          pnpm run check-type
